Expose connection class object to NetworkTemplate
ansible-collections/ansible.netcommon pull request #180
Opened 2020-11-24 19:12 UTC by GomathiselviS

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

##### SUMMARY

Inorder to get the network os version, connection class object needs to be accessed inside the rm_template file.
To achieve this, a base class has been added - RmbaseEngine which handles the connection to the device. This class is  inherited by ResourceModule and NetworkTemplate class.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-12-04 14:32 UTC, GomathiselviS commented
recheck

2020-12-11 17:49 UTC, Qalthos approved these changes

2021-01-07 13:25 UTC, ganeshrn approved these changes
Thanks for working on it. Changes look fine to me.

2021-01-07 13:46 UTC, NilashishC approved these changes

2021-01-08 07:57 UTC, NilashishC reviewed
To organize the classes in a better (more Python-ish) way, we can possibly have the following dir structure:
```
module_utils
-> network
   -> common
      -> rm_base
           -> __init__.py (RMBase)
           -> network_template.py (NetworkTemplate)
           -> resource_module.py (ResourceModule)
```

For backwards compatibility, we can keep the existing `network_template.py` and `resource_module.py` files, remove everything and just add the following respectively in it.
```
from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.network_template import (
    NetworkTemplate,
)
from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.resource_module import (
    ResourceModule,
)
```

2021-01-15 15:49 UTC, NilashishC commented on plugins/module_utils/network/common/resource_module_base.py
> +    ACTION_STATES = ["merged", "replaced", "overridden", "deleted"]
```suggestion
    ACTION_STATES = ["merged", "replaced", "overridden", "deleted",  "purged"]
```

2021-02-14 17:47 UTC, NilashishC requested changes

2021-02-14 17:47 UTC, NilashishC commented on plugins/module_utils/network/common/rm_base/resource_module.py
> +from __future__ import absolute_import, division, print_function
Missing copyright and licensing information.

2021-02-14 17:48 UTC, NilashishC commented on tox.ini
> +exclude = .git,.mypy_cache,.tox,tests/unit/compat/,tests/output/,plugins/module_utils/network/common/resource_module.py,plugins/module_utils/network/common/network_template.py
Why do we need this exclude?

2021-02-14 18:19 UTC, NilashishC commented on plugins/module_utils/network/common/network_template.py
> +from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.network_template import (
```
from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.network_template import (  # noqa: F401
    NetworkTemplate,
)
```

2021-02-14 18:19 UTC, NilashishC commented on plugins/module_utils/network/common/resource_module.py
> +from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.resource_module import (
```
from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.rm_base.resource_module import (  # noqa: F401
    ResourceModule,
)
```

2021-02-14 18:23 UTC, NilashishC commented on tox.ini
> +exclude = .git,.mypy_cache,.tox,tests/unit/compat/,tests/output/,plugins/module_utils/network/common/resource_module.py,plugins/module_utils/network/common/network_template.py
Okay, we can just skip the F401 checks on those two imports. I have commented on those files.

2021-02-17 13:37 UTC, Qalthos commented
recheck

2021-02-17 13:55 UTC, NilashishC approved these changes

2021-02-18 18:51 UTC, GomathiselviS commented
recheck

2021-02-19 02:23 UTC, rohitthakur2590 commented
recheck

2021-02-19 05:22 UTC, merged