fix changed in net_get
ansible-collections/ansible.netcommon pull request #199
Opened 2021-01-05 20:02 UTC by mtucker502

##### SUMMARY

Fixes #198 where net_get was missing default value for `changed`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
net_get

2021-01-06 13:18 UTC, Qalthos requested changes
You also need to add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) to document the issue being fixed.

2021-01-06 13:18 UTC, Qalthos commented on plugins/action/net_get.py
> +	changed = False
```suggestion
        changed = False
```

2021-01-06 17:44 UTC, mtucker502 commented
@Qalthos Committed the suggestion and added the changelog fragment

2021-01-06 20:17 UTC, Qalthos approved these changes

2021-01-06 20:19 UTC, Qalthos commented
recheck

2021-01-07 13:12 UTC, Qalthos commented
recheck

2021-01-11 13:10 UTC, Qalthos commented
recheck

2021-01-12 15:14 UTC, Qalthos commented
recheck

2021-01-14 12:54 UTC, Qalthos commented
recheck

2021-01-15 16:55 UTC, merged