Handle netconf plugin ncclient import error when running in FIPS mode
ansible-collections/ansible.netcommon pull request #243
Opened 2021-03-22 13:24 UTC by ganeshrn

*  While running in FIPS mode importing ncclient result in
   InternalError raised by cryptography
*  Refer https://github.com/ansible/ansible/pull/65477

##### SUMMARY

*  While running in FIPS mode importing ncclient result in
   InternalError raised by cryptography
*  Refer https://github.com/ansible/ansible/pull/65477 and https://github.com/ansible/ansible/pull/73992

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

connections/netconf.py

##### ADDITIONAL INFORMATION

```paste below

```

2021-03-24 12:51 UTC, Qalthos approved these changes

2021-03-25 23:19 UTC, Qalthos commented
recheck

2021-03-28 11:56 UTC, Qalthos requested changes

2021-03-28 11:56 UTC, Qalthos commented on changelogs/fragments/fips-ncclient-import-error.yaml
> +bugfixes:
```suggestion
---
bugfixes:
```

2021-03-29 03:30 UTC, rohitthakur2590 commented
recheck

2021-03-29 11:04 UTC, ganeshrn commented
recheck

2021-03-29 13:35 UTC, Qalthos approved these changes

2021-03-30 09:16 UTC, merged