[WIP] Add support for ProxyCommand with netconf connection
ansible-collections/ansible.netcommon pull request #268
Opened 2021-04-25 11:57 UTC by NilashishC

Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- ncclient 0.6.10 added support for passing a ProxyCommand object with jumphost settings to connect().
- This patch is aimed at leveraging the above so that users do not have to always depend on populating their SSH config file while using jumphosts.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

netconf.py

2021-04-26 12:51 UTC, Qalthos requested changes

2021-04-26 12:51 UTC, Qalthos commented on plugins/connection/netconf.py
> +      - {key: proxy_command, section: paramiko_connection}
I'm not sure if ssh is the right namespace for a common var or if paramiko would be better suited given why we need it.
```suggestion
      - {key: proxy_command, section: paramiko_connection}
      vars:
      - name: ansible_ssh_proxy_command
      - name: ansible_netconf_proxy_command
```

2021-05-12 15:26 UTC, Qalthos approved these changes

2021-05-12 15:41 UTC, NilashishC commented
recheck

2021-05-12 17:48 UTC, NilashishC commented
recheck

2021-05-13 05:03 UTC, NilashishC commented
recheck

2021-05-14 08:22 UTC, NilashishC commented
recheck

2021-05-14 15:56 UTC, NilashishC commented
recheck

2021-05-14 20:04 UTC, Qalthos commented
recheck

2021-05-15 08:20 UTC, merged