Added crlf/lf option to telnet
ansible-collections/ansible.netcommon pull request #440
Opened 2022-06-08 07:12 UTC by michaelpsomiadis

##### SUMMARY
Adds option to send a CLRF instead of a LF when talking to a device via telnet.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
telnet

##### ADDITIONAL INFORMATION
When attempting to use this plugin to send commands to a service that uses telnet I noticed that it required CLRF to "submit" the input (in this case being the username prompt). After just changing the strings to be CLRF I decided to add the functionality just incase someone else tries to use it in the future and hits this issue.
I've tested the code with the play that I was attempting to use it with success and original functionality should stay the same to not break existing plays.

Please let me know if you'd like me to make any changes. Thanks.

2022-07-15 00:33 UTC, jmontleon commented
I think this would fix https://github.com/ansible-collections/ansible.netcommon/issues/446 as well.

I hit the same issue and fixed it more or less the same way.

2022-10-27 18:10 UTC, Qalthos commented
Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

2022-11-21 16:19 UTC, Qalthos requested changes
Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? Thanks!

2023-07-29 12:12 UTC, michaelpsomiadis commented
Apologies, better late than never? decided to rebase and re-implement the changes because the latest version of the telnet module had been changed a little bit. Let me know if I've missed anything.

2023-09-05 13:41 UTC, Qalthos approved these changes

2023-09-06 13:15 UTC, merged