[network_cli] handle terminal errors
ansible-collections/ansible.netcommon pull request #447
Opened 2022-07-28 12:21 UTC by NilashishC

##### SUMMARY
- This change adds a new option to network_cli that determines what happens when there's a failure while setting parameters.
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/540

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
network_cli.py

2022-08-01 13:04 UTC, NilashishC commented
recheck

2022-08-01 13:29 UTC, Qalthos approved these changes

2022-08-02 12:06 UTC, Qalthos requested changes

2022-08-02 12:06 UTC, Qalthos commented on plugins/connection/network_cli.py
> +    choices: ["ignore", "warn", "fail"]
```suggestion
    choices: ["ignore", "warn", "fail"]
    version_added: 3.1.0
```

2022-08-02 12:25 UTC, Qalthos approved these changes

2022-08-02 14:39 UTC, merged