remove Tech preview of libssh
ansible-collections/ansible.netcommon pull request #451
Opened 2022-08-03 06:55 UTC by akira6592

##### SUMMARY

I heard that libssh is not Tech preview now in ansible network slack workspace.
SoI removed `Tech preview` of libssh,

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

libssh connection plugin document

2022-08-18 16:03 UTC, Qalthos commented
recheck

2022-08-18 22:40 UTC, akira6592 commented
@Qalthos In this case, should I create a changelog fragment?

2022-08-19 16:41 UTC, Qalthos commented
> @Qalthos In this case, should I create a changelog fragment?

Yes, you should. I would probably put this under `minor_changes` as although nothing has really changed, the change in status is still worth calling out in the changelog

2022-08-20 13:06 UTC, akira6592 commented
@Qalthos Thank you. I added changelog fragment as `minor_changes`.

2022-08-30 20:48 UTC, Qalthos requested changes

2022-08-30 20:48 UTC, Qalthos commented on changelogs/fragments/451-libssh-remove-tech-preview.yaml
> +minor_changes:
```suggestion
bugfixes:
```
Sorry for waffling on this when this is what I told you to do earlier. I don't think there's really a good section to put this under but it does need to get called out. Docs bugfixes are still bugfixes though.

2022-08-30 20:48 UTC, Qalthos approved these changes

2022-08-31 14:17 UTC, merged