Add simple regexp match for multiple prompt
ansible-collections/ansible.netcommon pull request #505
Opened 2023-01-22 09:52 UTC by Landrash

##### SUMMARY
Add a simple regexp match for multiple prompt with multiple answers.
This example could be used to for restarting a network device with a delay.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
ansible.netcommon.cli_command

##### ADDITIONAL INFORMATION
Matches prompt with regexp instead of full prompt to simplify multiple prompts with dynamic och convoluted output.

2023-03-31 19:39 UTC, Qalthos requested changes
Can you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) to your PR? The `doc_changes` section should be appropriate.

Thanks!

2023-03-31 19:39 UTC, Qalthos commented on plugins/modules/cli_command.py
> +     - y
You have an indentation error here
```suggestion
- name: Simple regexp match for multiple prompt, multiple answer(mandatory check for all prompts)
  ansible.netcommon.cli_command:
    command: reload in 5
    check_all: true
    prompt:
    - Save\?
    - confirm
    answer:
    - n
    - y
```

2023-04-01 17:41 UTC, Landrash commented
Added changelog fragment and synced branch with upstream to try and fix build failure.

2023-05-12 01:09 UTC, Qalthos requested changes

2023-05-12 01:09 UTC, Qalthos commented on changelogs/fragments/cli-command-module.yaml
> +trvial:
```suggestion
doc_changes:
```

2023-05-12 01:09 UTC, Qalthos commented on changelogs/fragments/cli-command-module.yaml
> +trvial:
```suggestion
doc_changes:
```

2023-05-12 01:11 UTC, Qalthos approved these changes

2024-03-06 10:21 UTC, NilashishC commented on plugins/modules/cli_command.py
@Landrash Hi! Just a heads up - we are still waiting for you to make the requested changes before we can merge this PR.

2024-07-19 10:37 UTC, merged